services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development

  db:
    image: mariadb:latest  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: micromanager
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # Volume persistant pour conserver les données
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql  # Script d'initialisation

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80" 
    environment:
      PMA_HOST: db  
      MYSQL_ROOT_PASSWORD: root  

volumes:
  db_data:  
