services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development

  db:
    image: mariadb:latest  # Utilise l'image MariaDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Remplace par un mot de passe sécurisé
      MYSQL_DATABASE: micromanager
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"  # Accès à phpMyAdmin via http://localhost:8080
    environment:
      PMA_HOST: db  # Référence au service "db"
      MYSQL_ROOT_PASSWORD: root  # Doit correspondre à celui défini pour MariaDB

volumes:
  db_data:  # Volume pour stocker les données de la base
